Foundations - Global styles
Jasoneto/rulea-bootcamp-01 pull request #1
Opened 2023-02-17 13:38 UTC by Jasoneto

HTML and CSS folders added, global styles added, typography added too

2023-02-17 13:42 UTC, Theweeksad approved these changes
NIce!!

2023-02-17 13:47 UTC, francoo-trainer commented
nice!

2023-02-17 14:08 UTC, johanmendezb requested changes
good job, couple of comments:
1. Add global css styles to a global css folder.
2. Bring back the index.html to the root of the project.
3. Change html folder name to something for contextual to the project like "flow", "step".
4. Remove all extra code that is not related to the ticket.(no action needed)

2023-02-20 21:14 UTC, Theweeksad approved these changes
I see that the code is in good condition.

2023-02-21 13:50 UTC, johanmendezb requested changes

2023-02-21 13:50 UTC, johanmendezb commented on CSS/Question-01.css
> +    font-size: 36px;
Line 2 and 3 should be located at global styles

2023-02-21 13:50 UTC, johanmendezb commented on CSS/Question-01.css
> +    font-size: 24px;
This should be located at global styles

2023-02-21 13:50 UTC, johanmendezb commented on CSS/Question-01.css
> +    font-size: 16px;
`font-size` property is already 16px since it is the browser default, please remove this line

2023-02-21 13:50 UTC, johanmendezb commented on CSS/main.css
> +    font-size: 36px;
Line 2 and 3 should be located at global styles

2023-02-21 13:50 UTC, johanmendezb commented on CSS/main.css
> +    font-weight: 400;
Line 7 and 8 should be located at global styles

2023-02-21 13:50 UTC, johanmendezb commented on CSS/main.css
> +    font-size: 16px;
`font-size` property is already 16px since it is the browser default, please remove this line

2023-02-21 13:50 UTC, johanmendezb commented on CSS/main.css
> +    font-weight: 400;
` font-weight`property is already 400 as the default, please remove this line

2023-02-21 13:50 UTC, johanmendezb commented on CSS/main.css
> +    font-size: 16px;
font-size property is already 16px since it is the browser default, please remove this line

2023-02-21 13:50 UTC, johanmendezb commented on CSS/main.css
> +    font-weight: 400;
font-weightproperty is already 400 as the default, please remove this line

2023-02-21 14:11 UTC, Theweeksad approved these changes
I see that everything is fine

2023-02-21 14:30 UTC, francoo-trainer commented
thanks for the changes!

2023-02-21 20:58 UTC, Theweeksad approved these changes
all it's good, nice job

2023-02-21 21:44 UTC, francoo-trainer reviewed
good contribution, thanks

2023-02-22 13:46 UTC, johanmendezb approved these changes
GJ

2023-02-22 15:38 UTC, francoo-trainer approved these changes

2023-02-22 16:07 UTC, Brayan1425 approved these changes
Changes are good

2023-02-23 13:58 UTC, merged