I added new styles to the homepage like margin and padding in the tag…
Jasoneto/rulea-bootcamp-01 pull request #2
Opened 2023-02-23 15:02 UTC by Jasoneto

I added new styles to the homepage like margin and padding in the tags p and h2, with the respetive BEM classes.

2023-02-24 15:35 UTC, Theweeksad approved these changes
nice!!

2023-03-02 14:48 UTC, johanmendezb requested changes
please review my comment, gj, thanks!

2023-03-02 14:48 UTC, johanmendezb commented on CSS/normalice.css
> +}
Please remove this `h1` properties.

2023-03-03 14:34 UTC, Theweeksad approved these changes
nice!

2023-03-07 13:30 UTC, johanmendezb approved these changes

2023-03-09 19:18 UTC, merged